import re

import inflect
p = inflect.engine()

# Capitalisation philosophy:
# https://discord.com/channels/1356178382106132570/1356180539522023498/1535338364667043840

# Note when creating a list of articles (NEW):
    # Remove some pages for sanity:
        # */Sound effects
        # */* Transcript
        # DW:*
        # RS:*
        # All 365 calendar dates ("1 January" etc)
        # Non-english e.g. 玻璃

        # As of 2026-08-09, there are 4873 actual articles to match on DW
        # after removing above + removing case duplicates.

    # Add any other non-article phrases you want to decapitalise, such as "Ingredients"

# Always preserve these capitalisations in article names.
# Each item should be either a string "noun" or array of [regex match, "noun"].
PROPER_NOUNS = [
    # Skills, which are often sub-words of other pages (like "magical")
    [r"\bAgility\b", "Agility"],
    [r"\bArtisan\b", "Artisan"],
    [r"(?<!special )\bAttack\b(?! weapon)", "Attack"],
    [r"\bConstruction\b", "Construction"],
    [r"\bCooking(?! range| pot| potion)\b", "Cooking"],
    [r"(?<!tree )\bFarming(?! plot| tool)\b", "Farming"],
    [r"(?:(?<!net )(?<!rod ))\bFishing\b(?! rod| net| tool| bait| node| spot| barrel)", "Fishing"],
    [r"\bMagic\b(?! carpet| weapon)", "Magic"],
    [r"\bMining\b", "Mining"],
    [r"\b(?<!de)Ranged\b(?! weapon)", "Ranged"],
    [r"\bRunecrafting\b", "Runecrafting"],
    [r"\bWoodcutting\b", "Woodcutting"],
    [r"\bPrayer\b(?! point)", "Prayer"],
    "Cape of Accomplishment",
    "Capes of Accomplishment",

    # Locations from recursive Category:Ashenfall
    "Adventurer's Guild",
    "Ashenfall",
    "Ashien",
    "Ashien's Watch",
    "Bleakfields Valley",
    "Bloodblight Castle",
    "Bloodblight Swamp",
    "Bramblemead Valley",
    "Bramblemead Village",
    "Brynmoor",
    "Chaktan Kara",
    "Coalridge Pass",
    "Colossal Wyrm Camp",
    "Crasorak Kara",
    "Crystalline Mesa",
    "Dowdun Reach",
    "Dragon's Run",
    "Druid's Cave",
    "Emberwood",
    "Fellhollow",
    "Fight Cave",
    "Forgotten Temple",
    "Fractured Plains",
    "Fractured Ruins",
    "Ghornfell",
    "Highlands Castle",
    "Hope's Fall",
    "Imaru's Tower",
    "Kalistrakthen Kara",
    "Keep of Blue Flames",
    "Kletterbuja Kara",
    "Lake of Lost Souls",
    "Lougrim's Shrine",
    "Nightmare Crucible",
    "Nightmare",
    "Crucible",
    "Outlook Ruins",
    "Purification Pool",
    "Runecrafting Guild",
    "Scorned Wilderness",
    "Silverthorn Keep",
    "Skeklac Kara",
    "Skekven Kara",
    "Stormtouched Highlands",
    "Takla Kara",
    "Temple Woods",
    "Thishepen Kara",
    "Umbral Sands",
    "Vekchenven Kara",
    "Velgar",
    "Velgar's Rise",
    "Vertentis Kara",
    "Whispering Swamp",
    "Witchwillow Range",
    # Plus some shortenings:
    "Bramblemead",
    "Bloodblight",
    "Dowdun",
    "Umbral",
    [r"Sands\b", "Sands"], # Don't match "Sandstone"
    "Highlands",
    # And agility courses:
    "Chasm Dash",
    "Fractured Ruins",
    "Thunder Assault",
    "Grave Run",
    "Tower Climb",
    "Lava Fields",
    # Sub-regions, many of which aren't listed in the category page:
    "Bleakfields Valley",
    "Coalridge Pass",
    "Dragon's Run",
    "Emberwood",
    "Emberwood Village",
    "Forgotten Temple",
    "Hope's Fall",
    "Lake of Lost Souls",
    "Silverthorn Keep",
    "Witchwillow Range",
    "The Approach",
    "The Bastion",
    "The Cathedral",
    "The Courtyard",
    "The Crypt",
    "The Demon Gate",
    "The Garrison",
    "The Grand Hall",
    "The Lake",
    "The Library",
    "The Menagerie",
    "The Nexus",
    "The Pastures",
    "Alcarrid Oasis",
    "Dunes of Uzzer",
    "Manafem Plains",
    "The Burning Spire",

    # Other places
    "Gielinor",
    [r"\bAbyss\b", "Abyss"], # not abyssal for some reason
    "Abyssal Space",
    "Blue Flame Keep",
    "Blueflame Keep",
    "Brynmoor Castle",
    "Menaphos",
    "Temple of", # e.g. Saradomin
    "Rememberance Shrine",
    "Uzzer",
    "Antumnos",
    "Magrawn",
    "Brakka's Folly",
    "Grand Hall",
    "Kharid", # ...ian
    "Wizard's Guild",
    "Magic Institute",
    "Wizard's Tower",
    "King's Pass",
    "Death's Temple",

    # Shops
    "Death's Exchange",
    "Evil Emporium",

    # Quests: https://dragonwilds.runescape.wiki/w/Template:Quests?action=edit
    "First Steps",
    "Getting Started",
    "Ratcatcher",
    "Rune Mysteries",
    "Dragon Slayer",
    "Withering Heights",
    "Black Knight's Fortress",
    "Icthlarin's Little Helper",
    "Growing Pains",
    "Shrimp Catcher",
    "Restless Ghosts",
    "Goblin Diplomacy",
    "Highlighting the Problem",
    "Granite Mauled",
    "Heartstrings",
    "Dog Days",
    "Cook's Assistant",
    "A Room With A Garou",
    "Animal Magnetism",
    "A Melody Remembered",
    "Even More Restless Ghosts",
    "The Wild Hunt",
    "Seeking Salvation",
    "Things That Go Boom In The Night",
    "Doric's Quest",
    "Letters for the Dead",
    "What Remains is Written",
    "Mirror, Mirror",
    "Biohazard",
    "Wanted!",
    "What's Theirs is Mine!",
    "Contact!",
    "Mapping The Sands I",
    "Mapping The Sands II",
    "Brink of Extinction",
    # Activities: https://dragonwilds.runescape.wiki/w/Template:Activities?action=edit
    "Statues of Saradomin",
    "X Marks the Spot",
    # More:
    "The Great Body Robbery",
    "Warding Off Danger",
    "Rogue Trader",
    "Rag and Bone Garou",
    "The Mirror Cracked",
    "Kuldra's Saga",
    "The Collector Calling",

    # Dates
    "First Age",
    "Second Age",
    "Third Age",
    "Fourth Age",
    "Fifth Age",
    "Sixth Age",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",

    # Events
    "Anima Twist",
    "Withering",
    "Human-Garou War",
    "Day of Purple Feathers",
    "Dragon Rebellion",
    "God War",
    "Schism",
    "Mark Day",

    # Gods
    "Armadyl",
    "Bandos",
    "Big High War God",
    "Guthix",
    "Saradomin",
    "Zamorak",
    "Icthlarin",
    "Icthlarian",

    # Group/tribe/order names
    # (not races: dragonkin, garou, goblin, kalphite all lowercase)
    "Amalgamated",
    "Dorgeshuun",
    "Black Knight",
    "White Knight",
    "Knights of Saradomin",
    "Temple Knight",
    "Lunar Garou",
    "Moon Garou",
    "Dactyl",
    "Elder God",
    "Cabal",
    "Children of Shadows",
    "Bronze Advisors",
    "Glass Knives",
    "Rasmodel", # sometimes plural (Rasmodel family / Rasmodels)
    "Demon's Share",
    "Dragon Riders",

    # TzHaar creatures, for some reason: https://dragonwilds.runescape.wiki/w/KotHaar
    "TzHaar",
    "KotHaar",
    "KotHaar-Xil",
    "KotHaar-Kal",
    "KotHaar-Ket",
    "KotHaar-Hur",
    "Tok-Xil",

    # Weapon eponyms
    "Swingslash",
    "Skullsplitter",
    "Titan's Wrath",
    [r"(?<!mirror )\bLens\b", "Lens"], # A specific Elder artifact

    # Other names (often first names from below)
    "Elidinis",
    "Fuzan",
    "Noggin",
    "Oculus",
    "Ravanna",
    "Velgar",
    "General Velgar",
    "Victoria",
    # "Death",
    "Death (Grim Reaper)",
    "Grim Reaper",
    "Harold Death Esquire",
    "Postie Pete",
    "Parcel Pete",
    [r"\bPete\b", "Pete"],
    "Caratacus",
    "Caratacus the Elder",
    "Karibdos",
    [r"\bAva\b", "Ava"], # Careful, it's short
    "Wild Knight",
    "Fire-Touched",
    "Valerius",
    "Delrom",
    "Manktongue",
    "Pulpknuckle",
    "Slopfinger",
    "Xikotal",
    "Iasadair - The Merchant",
    "Iasadair",
    "Beartach - The Merchant",
    "Beartach",
    "Domri - The Merchant",
    "Domri",
    "Lehran - The Archaeologist",
    "Lehran",
    "Hedric - The Hunter",
    "Hedric",
    "Lagra - The Butcher",
    "Lagra",
    "Laguna - The Bard",
    "Laguna",
    "Manathep - The Bereaved",
    "Manathep",
    "Moon Sprite Shaman - Anamcara",
    "Anamcara",
    "Muncher",
    "Wise Old Man",
    "Archmage Alric",
    "Alric",
    "Lord Rasmodel",
    "Dreaming Stone",
    "Stone of Jas",
    "Titan", # of Black Knight Titan
    "Garou King",
    # "Kalphite Queen", # no, there are multiple in Ashenfall
    "King Black Dragon",
    "Queen Black Dragon",
    "Rat Master Skrexis",
    "Edna",
    "KotHaar-Hok-Zi",
    "Doctor Fenkenstrain",
    "Eleanor Scathe",
    "Blightscale",
    "Ulgo",
    "Reforged Zi",
    [r"\bZi\b", "Zi"],
    "Brassica Prime",
    "Captain Rainer",
    "Commander Zilyana",
    "Zilyana",
    "Efina - The Lost",
    "Efina",
    "Dearg Due",
    "High Queen of the Garou",
    "High Queen",
    "Queen Kuldra",
    "God Eater",
    "God-Eater",
    "Dragon Queen",
    "Queen of Ashes",
    "Sun Demon",
    "Demon of Embers",
    "Demon of the Suns",
    "Elder Kiln",
    "Duke",
    "Manafem Elder",
    "Razlem, the Deranged",
    "River Goddess",
    "Goddess of the River",
    "Soul Eater",
    "Soul-Eater",
    "Meya",
    "Samuel Malcifer",
    "Fido",
    "Lurch",
    "Gnasher",
    # "Tiny",
    "Rufus",
    "Buddy",
    "Boggs",
    "Curly",
    "Nosey",
    # "Patch",
    [r"\bPip\b", "Pip"],
    "Reek",
    "World Guardian",
    "Guardians of Guthix",
    "Lagra",
    "Blood Witch",
    "Magpie King",
    "Shaun",
    "Nolan Scathe",

    # List of NPCs: https://dragonwilds.runescape.wiki/w/Non-player_character?action=edit
    "Atilius Rasmodel",
    "Abraxus",
    "Abraxus The Eternal",
    "Avisk",
    "Bilegut",
    "Cathan",
    "Doric",
    "Finn",
    "Houndmaster Rexiton",
    "Imaru",
    [r"\bKay\b", "Kay"], # Careful, it's short
    "Lazina",
    "Putrilius",
    "Sergeant Blister",
    "Spitfoot",
    "Spittletoe",
    "Snotpit",
    "OffalFoot",
    "Summoner Flament",
    "Vannaka",
    "Warren",
    "Wormelbow",
    "Zanik",
    "Farmer Fred",

    # NPCs that do not appear in-game
    "Aidan",
    "Ansel",
    "Artorius Flamhanger",
    "Ashien",
    "Auburn Ocelot",
    "Avisk",
    "Bilar Amaris",
    "Brakka",
    "Callius Waithe",
    "Claus",
    "Count Valingard",
    "Cynthia Valtis",
    "Dahnu",
    "Derien",
    "Drorkar",
    "Elias Oculus",
    "Eric",
    [r"\bEva\b", "Eva"], # Careful, it's short
    "Falistrius",
    "Finn",
    "Frode",
    "Gahl",
    "Glass Knife",
    "Gothren Actillian",
    "Gregor Volrath",
    "Haager",
    "Henrietta",
    "Hokistix",
    "Holtz",
    "Ignatius Wormwood",
    [r"\bIsla\b", "Isla"], # Careful, it's short
    "Jenniva Milgrim",
    "Jillian Varden",
    "Kessel",
    "Karia",
    "Kethren",
    "King Raluh",
    "King Rolthar",
    "Kuldra",
    "Lacrussa",
    "Lavernius",
    "Leander",
    "Lina Hesperian",
    "Lionel",
    "Lord Gawurin",
    "Lougrim",
    "Malgo",
    "Mallory",
    "Mayev",
    "Mia Larsdottir",
    "Mittens",
    "Moragrin",
    "Mouldfinger",
    "Mrs Hyacinth",
    "Nightingale",
    "Noggin",
    "Olga Skulltaker",
    "Olis",
    "Orik the Bear",
    "Otho",
    "Ramus Lumen",
    "Rasthin",
    "Ravanna",
    "Sadia Vulketra",
    "Shana",
    "Shatterfang",
    "Sir Lear",
    "Sir Percival Lateef",
    "Skrexis",
    "The Cairn",
    [r"\bUlv\b", "Ulv"], # Careful, it's short
    "Vemmeck",
    "Vesk",
    "Victoria Thistlethwaite",
    "Viika",

    # Emotes
    "Grab Attention",

    # Jagex: https://dragonwilds.runescape.wiki/w/Category:Jagex
    "Ally Banayoti",
    "Community Campfire",
    "Jagex Audio Team",
    "Karlotta Skagfield",
    "Mod Aaart",
    "Mod Arclaw",
    "Mod Ark",
    "Mod Bakes",
    "Mod bitf0x",
    "Mod Blaze",
    "Mod Cerberus",
    "Mod Colibri",
    "Mod Corvin",
    "Mod Cyphus",
    "Mod Debris",
    "Mod Deluxe",
    "Mod Dodds",
    "Mod Dolan",
    "Mod Doom",
    "Mod Dutch",
    "Mod ExOh",
    "Mod Ice Cream",
    "Mod Joker",
    "Mod JT",
    "Mod Kodo",
    "Mod Labbo",
    "Mod Mossdog",
    "Mod Nomad",
    "Mod Nosfer",
    "Mod Oliveira",
    "Mod Orion",
    "Mod Osborne",
    "Mod Pointy",
    "Mod PugZ",
    "Mod Raven",
    "Mod Rook",
    "Mod Sharky",
    "Mod Sylvan",
    "Mod Zephyer",
    "Mod Zombie",
    "Peter Michael Davison",
    # Plus others not in category:
    "Jagex",
    "RuneScape",
    "Dragonwilds",
    "Ashton Mills",
    "Andrew Dodds",
    "Mod Gifted",
    "RuneFest",
    "Alpha Test",
    "Alpha Challenge Cape DLC",

    # Special attacks: TODO
    "Abyssal Snare",

    # Spells: https://dragonwilds.runescape.wiki/w/Special:Bucket?bucket=infobox_spell&select=*&where=&limit=500&offset=0
    "Windstep",
    "Tempest Shield",
    "Enchant Weapon: Fire",
    "Enchant Weapon: Air",
    "Rocksplosion",
    "Summon Stone Spirits",
    "Axtral Projection",
    "Splinter",
    "Bark To Bones",
    "Superheat",
    "Magical Mending",
    "Eye of Oculus",
    "Summon Shelter",
    "Personal Chest", # Removed unnecessary trailing "(spell)"
    "Internal Alchemy",
    "Bones to Peaches",
    "Fire Spirit",
    "Surge",
    "Confuse",
    "Snare",
    "Spectral Arrows",
    "Venomous Trapper",
    "Humidify",
    "Uproot",
    "Runes to Rune Essence",
    "Summon Elemental Spirits",
    "Fishing Frenzy",
    "Infernal Rod",
    "Fishnado",
    "Divine Rock",
    "Trunk Totem",
    "Recall",
    "Phase Dash",
    "Rapid Growth",
    "Mucksplosion",

    # Perks: https://dragonwilds.runescape.wiki/w/Template:Perks?action=edit
    "Arcane Aligned",
    "Evasion",
    "Ferocious Fighter",
    "Fleet Footed",
    "Quenched",
    "Relentless Ranger",
    "Soul Food",
    "Stalwart Shield",
    "Frosted Flavours",
    "Coagulated",
    "Foreman's Feast",
    "Fungal Fortitude",
    "Grounded",
    "Meaty Meal",
    "Knowledgable Nourishment",
    "Knowledgeable Nourishment", # Wrong but common
    "Steadfast Stomach",
    "Soul Food",
    "Ravenous",
    "Sea Legs",
    "Warding Fish",
    "Sea Life",
    "Sugar Rush",
    "Frosted Flavours",
    # Not "Antipoison" which is more common as an item
    # Not "Antifire" which is more common as an item
    "Focused Strikes",
    "Focused Casting",
    "Focused Artisan",
    "Focused Attack",
    "Focused Construction",
    "Focused Cooking",
    "Focused Mining",
    "Focused Runecrafting",
    "Focused Woodcutting",
    "Focused Farming",
    "Focused Fishing",
    "Focused Agility",
    "Lumberjack",
    "Quarrymaster",
    # Not "Stamina Potion" which is more common as an item
    "Antipoison II",
    "Antifire II",
    "Focused Artisan II",
    "Focused Attack II",
    "Focused Construction II",
    "Focused Cooking II",
    "Focused Mining II",
    "Focused Runecrafting II",
    "Focused Woodcutting II",
    "Focused Farming II",
    "Focused Fishing II",
    "Focused Agility II",
    "Lumberjack II",
    "Quarrymaster II",
    # Construction: https://dragonwilds.runescape.wiki/w/Template:Construction?action=edit
    "Creature Comforts",
    "Middle Ground",
    "Fine Details",
    "Sacred Geometry",
    "Mighty Oak",
    # Agility: https://dragonwilds.runescape.wiki/w/Template:Agility?action=edit
    "Double Jump",
    "Hopper",
    "Common Burrower",
    "Air Dash",
    "Breakfall",
    "Wind Stomp",
    "Wild Burrower",
    "Reactive Recall",
    # "Nomad",
    "Backpacker",
    "Greater Breakfall",
    "Dark Burrower",
    "Desert Burrower",
    # "Explorer",
    "Razor-backed Burrower",
    "Trailblazer",
    # Runecrafting: https://dragonwilds.runescape.wiki/w/Template:Runecrafting?action=edit
    "Summon Elemental Spirits",
    "Runes to Rune Essence",
    "Fire Spirit",
    "Greater Elemental Spirits",
    "Runes to Rune Essence",
    "Runes to Rune Essence Upgrade",
    "Pure Essence",
    "Lesser Anima Siphoning",
    "Essential Strength",
    "Greater Anima Siphoning",
    # "Attunement Phase Duration", # listed repeatedly as a duration rather than the perk
    "Lesser Infusion Duration",
    "Better Infusion Duration",
    "Greater Infusion Duration",
    "Air Efficiency",
    "Astral Efficiency",
    "Water Efficiency",
    "Earth Efficiency",
    "Fire Efficiency",
    "Nature Efficiency",
    "Law Efficiency",
    # Attack: https://dragonwilds.runescape.wiki/w/Template:Attack?action=edit
    # "Parry",
    "Melee Weapon Special Actions",
    "Weapon Expertise",
    "Adaptability",
    # Magic: https://dragonwilds.runescape.wiki/w/Template:Magic?action=edit
    "Secondary Attacks",
    # "Water Magic",
    # "Fire Magic",
    "Arcane Expertise",
    "Runic Refund",
    "Afterimage",
    "Magical Focus",
    "Greater Confuse",
    # Ranged: https://dragonwilds.runescape.wiki/w/Template:Ranged?action=edit
    "Quick Action",
    "Trick Shot",
    "Toxic Behaviour",
    "Hunter's Sense",
    "Make 'Em Bleed",
    "Crossbow Trick Shot",
    "Enchanted Crossbow Bolts",
    "Venomous Trapper",
    "Fire Starter",
    # Mining: https://dragonwilds.runescape.wiki/w/Template:Mining?action=edit
    "Lift With Your Hips",
    "Ultimate Burst",
    "Gem Prospector",
    "Mine Crumbled Walls",
    "Detect Ore + Clay",
    "Not-So-Heavy Metal",
    # "Divine Rock",
    "Accelerated Veins",
    "Ingot Weight Reduction",
    # Fishing: https://dragonwilds.runescape.wiki/w/Template:Fishing?action=edit
    "Troubled Waters",
    "Greater Fishnado",
    # Farming: https://dragonwilds.runescape.wiki/w/Template:Farming?action=edit
    "Cleansing Rain",
    "Harvester",
    "Overgrowth Aura",
    "Speedy Farmer",
    # Artisan: https://dragonwilds.runescape.wiki/w/Template:Artisan?action=edit
    "Decorated Adventurer",
    # Cooking: https://dragonwilds.runescape.wiki/w/Template:Cooking?action=edit
    "Amateur Culinaromancer",
    "Adept Culinaromancer",
    "Culinary Confidence",
    "Grill Master",
    "Fancy Cookware",
    "Yes, chef!",
    "Teamonger",
    # Woodcutting: https://dragonwilds.runescape.wiki/w/Template:Woodcutting?action=edit
    "Chop Thorny Vines",
    # Other
    "Burning Endurance",
    "Ferocious Furnace",

    # Status effects: https://dragonwilds.runescape.wiki/w/Template:Statuses?action=edit
    # Many of these are also used in sentences like "withered" so should not be caps.
    [r"\bFresh Start\b", "Fresh Start"],
    [r"(?<!summoned )\bShelter\b", "Shelter"],
    [r"\bCosiness\b", "Cosiness"],
    [r"\bBleed\b", "Bleed"],
    [r"\bBurning\b", "Burning"],
    [r"\bEncumbered\b", "Encumbered"],
    [r"\bFatigue\b", "Fatigue"],
    [r"(?<!weapon )\bPoison\b(?! ichor| rock)", "Poison"],
    [r"\bShocked\b", "Shocked"],
    [r"\bSoulscourge\b", "Soulscourge"],
    [r"\bWater Wading\b", "Water Wading"],
    [r"\bWither\b", "Wither"],
    [r"\bScorch\b(?! leather)", "Scorch"],
    [r"\bOver Eating\b", "Over Eating"],
    # [r"\bLifeward\b", "Lifeward"], # No, this is like "health"

    # Book titles: https://dragonwilds.runescape.wiki/w/Template:Tomes and https://dragonwilds.runescape.wiki/w/Category:Quest_Items
    "The Pride of the Avernic",
    "The Importance of Chaos",
    "Aetheric Fundamentals, a Primordial Primer",
    "The Wrath of Baba Potterington",
    "Leonard the Bound",
    "Eventide - A New Spawn",
    "Coclear Malificarum",
    "The Binding of Ib",
    "Tome of Attack - Vol 1",
    "Tome of Attack - Vol 2",
    "Tome of Agility - Vol 1",
    "Tome of Agility - Vol 2",
    "Tome of Construction - Vol 1",
    "Tome of Construction - Vol 2",
    "Tome of Cooking - Vol 1",
    "Tome of Cooking - Vol 2",
    "Tome of Farming - Vol 1",
    "Tome of Farming - Vol 2",
    "Tome of Fishing - Vol 1",
    "Tome of Fishing - Vol 2",
    "Tome of Magic - Vol 1",
    "Tome of Magic - Vol 2",
    "Tome of Mining - Vol 1",
    "Tome of Mining - Vol 2",
    "Tome of Ranged - Vol 1",
    "Tome of Ranged - Vol 2",
    "Tome of Runecrafting - Vol 1",
    "Tome of Runecrafting - Vol 2",
    "Tome of Volcano",
    "Tome of Woodcutting - Vol 1",
    "Tome of Woodcutting - Vol 2",
    "Tome of the Artisan - Vol 1",
    "Tome of the Artisan - Vol 2",
    "Tome of the Dragon Slayer",
    "Tome of the Titan",
    "Tome of the Undying",
    # More:
    "The Wolf and the Goddess",
    "The Tale of the Ghost Wolves",
    "The Gospel of Zamorak",
    "Forbidden Scroll",
    "Castle Extra",
    "Hall of Heroes",

    # Music tracks: https://dragonwilds.runescape.wiki/w/Category:Music_tracks
    "A Wild World To Tame",
    "Ashenfall Nocturne 1",
    "Ashenfall Nocturne 2",
    "Beyond Nightfall",
    "Busy Getting To Work",
    "Cairn Toul",
    "Ceridwen",
    # Not "Combat (music)", too generic
    "Death's Domain",
    "Dragon Terror",
    "Dungeon Explore",
    "Echoes on the Wind",
    "Explore Chill",
    "Explore Ghornfell",
    "Explore Highlands",
    "Explore YesterYear",
    "Garou Camp (Combat)",
    "Garou Camp (Explore)",
    "Goblin Camp (Combat)",
    "Goblin Camp (Explore)",
    # Not "Harmony", too generic
    "Heroic Anticipation",
    "Into The Wilds (Main Theme)",
    "Into The Wilds",
    "Magical Busy",
    # Not "Medieval", too generic
    "Melodi Fresci",
    "Menu Chill",
    "Morytania",
    "Mystery Curiosity",
    "Mystery Magic",
    "Primitive Martial",
    "Primitive Ritual",
    "Restless Ghosts",
    # Not "Sacred", too generic
    "Sea Shanty ii",
    "Starlit Voyage",
    "Swamp Explore",
    "Tinkering Smithing",
    # Not "Village", too generic
    "Withering Wastes",

    # Achievements: https://dragonwilds.runescape.wiki/w/Steam_Achievements?action=edit
    "Steam achievement",
    "Swift Pick",
    "One Misthalin Star",
    "Chop Chop",
    "Stab, Slash, Crush!",
    "Crafting to Your Own Rune",
    "Sheltered",
    "Not today!",
    "Singed!",
    "Strike True",
    "Fred would be proud",
    "Catch of the Day",
    "Winner Winner Fish Dinner",
    "Medal Winner",
    "Honed Edge",
    "I'll Just Watch",
    "Master Huntsman",
    "It's all Mine!",
    "You Axed for It",
    "Mend it like...",
    "Eye can see my house from here!",
    "Two Misthalin Stars",
    "No Runefunds!",
    "Gotta Patch 'Em All",
    "Frenzied",
    "Medal Collector",
    "Sharp and Shiny",
    "All Buffed Up",
    "Helping around the farm",
    "Bark at the Moon",
    "Dragon Slayer",
    "Don't fear the Reaper",
    "Withering Heights",
    "Mages & Knights & Demons, oh my!",
    "Black Knight's Fortress",
    "Icthlarin's Bigger Helper",
    "Scorching Sands",
    "Melee Master",
    "Dionysius' Disciple",
    "Thrill of the Hunt",
    "Everything is Oresome",
    "Everything is Treemendous",
    "The School of Jewels",
    "Absolute Planker",
    "Three Misthalin Stars",
    "Altar Native",
    "Granny's Favourite Farmer",
    "Maximum Effishiency",
    "Amazingly Acrobatic",

    # Consoles/tech
    # not Steam, too generic?
    "XBOX",
    "Series X",
    [r"\bX and S\b", "X and S"],
    [r"\bX/S\b", "X/S"],
    "PlayStation",
    "Shockbyte",
    [r"\bPC\b", "PC"],
    "Windows",
    [r"\bMac\b", "Mac"],
    "Macintosh",
    "Linux",
    "Creative Mode",

    # Acronyms
    [r"\bNPC\b", "NPC"],
    [r"\bNPCs\b", "NPCs"],
    [r"\bPvP\b", "PvP"],
    [r"\bDLC\b", "DLC"],
    [r"\bN/A\b", "N/A"],
    [r"\bHP\b", "HP"],
    [r"\bSFX\b", "SFX"],
    [r"\bUI\b", "UI"],
    [r"\bXP\b", "XP"],

    # Other
    "Soulscourge",
    [r"(?:\w)/Level up table", "/Level up table"],
    [r"(?:\w)/Strategies", "/Strategies"],
    [r"(?:\w)/Mechanics", "/Mechanics"],
    "MOUNT:",
    "PATTERN:",
    "PLAN:",
    " of ",
    "'s ",
]

# Precompile regexes for speed.
PROPER_NOUN_PATTERNS = [
    (
        re.compile(noun[0], re.IGNORECASE),
        noun[1],
    ) if isinstance(noun, list) else (
        re.compile(re.escape(noun), re.IGNORECASE),
        noun,
    )
    for noun in PROPER_NOUNS
]

def restore_proper_nouns(text):
    for pattern, replacement in PROPER_NOUN_PATTERNS:
        # Fast case
        if replacement.lower() not in text.lower():
            continue

        # Slower case
        text = pattern.sub(replacement, text)

    return text

# This method fixes the weird behavior of inflect, e.g.
#    >>> p.singular_noun("cows")
#    'cow'
#    >>> p.singular_noun("cow")
#    False # wrong
def _singular(word):
    word = p.singular_noun(word) or word
    return word

def singular(text):
    tokens = text.split()
    last_word = tokens.pop()
    tokens.append(_singular(last_word))
    return " ".join(tokens)

# This method fixes the weird behavior of inflect, e.g.
#    >>> p.plural_noun("cow")
#    'cows'
#    >>> p.plural_noun("cows")
#    'cowss' # wrong
def _plural(word):
    if p.singular_noun(word): # returns False if already singular
        return word # already plural

    word = p.plural_noun(word)
    return word

def plural(text):
    # e.g. "body => bodies" but "Body => Bodys"
    if has_caps(text):
        print("WARN: text must be lowercase to pluralize properly: " + text)

    tokens = text.split()
    last_word = tokens.pop()
    tokens.append(_plural(last_word))
    return " ".join(tokens)

def has_caps(text):
    return any(c.isupper() for c in text)
