"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://dragonwilds.runescape.wiki
  name = rsdw

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'rsdw'
    langs = {
        'en-gb': 'dragonwilds.runescape.wiki',
    }

    def scriptpath(self, code):
        return {
            'en-gb': '',
        }[code]

    def protocol(self, code):
        return {
            'en-gb': 'https',
        }[code]
